// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package assets

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icons/blue.svg
var ResourceBlueSvgData []byte
var ResourceBlueSvg = &fyne.StaticResource{
	StaticName:    "icons/blue.svg",
	StaticContent: ResourceBlueSvgData,
}

//go:embed icons/yellow.svg
var ResourceYellowSvgData []byte
var ResourceYellowSvg = &fyne.StaticResource{
	StaticName:    "icons/yellow.svg",
	StaticContent: ResourceYellowSvgData,
}

//go:embed icons/green.svg
var ResourceGreenSvgData []byte
var ResourceGreenSvg = &fyne.StaticResource{
	StaticName:    "icons/green.svg",
	StaticContent: ResourceGreenSvgData,
}

//go:embed icons/orange.svg
var ResourceOrangeSvgData []byte
var ResourceOrangeSvg = &fyne.StaticResource{
	StaticName:    "icons/orange.svg",
	StaticContent: ResourceOrangeSvgData,
}

//go:embed icons/purple.svg
var ResourcePurpleSvgData []byte
var ResourcePurpleSvg = &fyne.StaticResource{
	StaticName:    "icons/purple.svg",
	StaticContent: ResourcePurpleSvgData,
}

//go:embed icons/fox.svg
var ResourceFoxSvgData []byte
var ResourceFoxSvg = &fyne.StaticResource{
	StaticName:    "icons/fox.svg",
	StaticContent: ResourceFoxSvgData,
}

//go:embed icons/star.svg
var ResourceStarSvgData []byte
var ResourceStarSvg = &fyne.StaticResource{
	StaticName:    "icons/star.svg",
	StaticContent: ResourceStarSvgData,
}

//go:embed icons/target.svg
var ResourceTargetSvgData []byte
var ResourceTargetSvg = &fyne.StaticResource{
	StaticName:    "icons/target.svg",
	StaticContent: ResourceTargetSvgData,
}
